# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QBrush, QPixmap
from PyQt5.QtWidgets import QMessageBox

import WaterMark  # import module
import renamegai


class Ui_MainWindow(object):
    def __init__(self):
        self.pushButton = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(507, 270)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(18)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/title.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 60, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: rgb(100, 149, 237);color: rgb(244, 255, 244);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 130, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(100, 149, 237);color: rgb(247, 254, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(352, 190, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(100, 149, 237);color: rgb(240, 253, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        palette = QtGui.QPalette()
        # Set the form background adaptive
        palette.setBrush(MainWindow.backgroundRole(), QBrush(
            QPixmap("image/back.png").scaled(MainWindow.size(), QtCore.Qt.IgnoreAspectRatio,
                                             QtCore.Qt.SmoothTransformation)))
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(True)  # Set autofill background

        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image batch processor"))
        self.pushButton.setText(_translate("MainWindow", "Add watermark"))
        self.pushButton_2.setText(_translate("MainWindow", "Double naming"))
        self.pushButton_3.setText(_translate("MainWindow", "Software Introduction"))

        # watermark interface
        self.pushButton.clicked.connect(self.openMark)
        # rename interface
        self.pushButton_2.clicked.connect(self.openRename)
        # Software introduction
        self.pushButton_3.clicked.connect(self.about)

    # Open the watermark form

    def openMark(self):
        self.another = WaterMark.Ui_MainWindow()  # Create a watermark form object
        self.another.show()  # show form

    # Open the rename form

    def openRename(self):
        self.another = renamegai.window()  # Create rename form object
        # self.another.mainloop()#event loop

    # About this software

    def about(self):
        QMessageBox.information(None, 'About this software', 'Image batch processor is a tool software that provides daily work,'
                                               'With this software, you can easily add text watermarks and image watermarks to pictures,'
                                               'And you can customize the addition position and transparency; in addition, you can also pass'
                                               'The software renames image files, supports uppercase, lowercase file names, and'
                                               'Image files are numbered according to custom templates.', QMessageBox.Ok)


# main method
if __name__ == '__main__':
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()  # Create a form object
    ui = Ui_MainWindow()  # Create a form object designed by PyQt5
    ui.setupUi(MainWindow)  # Call the method of the PyQt5 form to initialize the form object
    MainWindow.show()  # show form
    sys.exit(app.exec_())  # Exit the process when the program closes
